name: TrifiSkillManager
main: facejup.skillpack.main.Main
description: fuck bitches get money
version: 69
depend: [SkillAPI, Citizens, Vault]
author: notyoubitch
commands:
  bind:
    description: ahahhhh
    usage: /<command>
  cast:
    description: ahahhhh
    usage: /<command>
  skills:
    description: ahahhhh
    usage: /<command>
  shop:
    description: ahahhhh
    usage: /<command>